name: Backup Match Data

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行
  workflow_dispatch:     # 允许手动触发

permissions:
  contents: write
  actions: write        # 添加上传 artifacts 的权限

jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        
      - name: Create backup directory
        run: |
          mkdir -p backup/matches
          mkdir -p backup/teams
        
      - name: Backup data
        run: |
          # 备份当前比赛数据
          cp data/matches/current.json backup/matches/
          # 备份历史比赛数据
          cp -r data/matches/history backup/matches/
          # 备份球队数据
          cp data/teams/*.json backup/teams/
          
      - name: Create backup archive
        run: |
          tar -czf backup_${{ steps.date.outputs.date }}.tar.gz backup/
          
      - name: Upload backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: match-data-backup-${{ steps.date.outputs.date }}
          path: backup_${{ steps.date.outputs.date }}.tar.gz
          retention-days: 30
          
      - name: Cleanup
        if: always()
        run: |
          rm -rf backup/
          rm -f backup_${{ steps.date.outputs.date }}.tar.gz
